spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
sonar:
  host:
    url: "http://localhost:9000"
  login: "squ_834516628a3dcd4bf4c93f41130c58a7ef1c18eb"