version: '3.8'

services:

  database:
    image: postgres:15.2-alpine
    container_name: "happening-now_database"
    ports:
      - "5445:5432"
    restart: always
    env_file: .env
  sonar:
    image: sonarqube:latest
    container_name: "happening-now_sonar"
    ports:
      - "9000:9000"



