version: '3.8'

services:

  database:
    image: postgres:15.2-alpine
    container_name: "hn-database"
    ports:
      - "5445:5432"
    restart: always
    env_file: .env
  sonar:
    image: sonarqube:10.6-community
    container_name: "hn-sonar"
    ports:
      - "9000:9000"